stages:
  - deployLocal
  - testArticleService
  - testTopicService
  - testUserService
#  - sonarqube

build:
  stage: deployLocal
  tags: 
    - CI/CD
  script:
    - echo docker compose deployment
    - cd Backend
    - docker compose up 
  when: manual


testArticleService: 
  image: python:3.9-slim-buster
  stage: testArticleService
  tags: 
    - docker_runner
  script:
    - echo "This is test pipepline for article_service"
    - cd Backend/article_service
    - pip install -r requirements.txt
    - pytest

testTopicService:
  stage: testTopicService
  tags: 
    - CI/CD
  script:
    - echo "This is test pipepline for topic_service"

testUserService:
  stage: testUserService 
  tags: 
    - CI/CD
  script:
    - echo "This is test pipepline for user_service"





  
