stages:
  - dockerComposeLocalDeploy
  - testArticleService
  - testTopicService
  - testUserService
#  - sonarqube

build:
  image: ubuntu:latest
  stage: dockerComposeLocalDeploy
  tags: 
    - docker_runner
  script:
    - echo "Docker compose deployment"
    - cd Backend
    - cp $ENV_FILE_DOCKER_COMPOSE .env
    - docker compose up 
  when: manual


testArticleService: 
  image: python:3.9-slim-buster
  stage: testArticleService
  tags: 
    - docker_runner
  script:
    - echo "This is test pipepline for article_service"
    - cd Backend/article_service
    - echo $ENV_FILE_ARTICLE_SERVICE
    - cp $ENV_FILE_ARTICLE_SERVICE .env_local
    - pip install -r requirements.txt
    - pytest
  only:
    changes:
      - Backend/article_service

testTopicService:
  stage: testTopicService
  tags: 
    - CI/CD
  script:
    - echo "This is test pipepline for topic_service"
    - cd Backend/topic_service
    - cp $ENV_FILE_TOPIC_SERVICE .env_local
    - pip install -r requirements.txt
    - pytest
  only:
    changes:
      - Backend/topic_service

testUserService:
  stage: testUserService 
  tags: 
    - CI/CD
  script:
    - echo "This is test pipepline for user_service"
    - cd Backend/user_service
    - cp $ENV_FILE_USER_SERVICE .env_local
    - pip install -r requirements.txt
    - pytest
  only:
    changes:
      - Backend/user_service





  
