stages:
  - dockerComposeLocalDeploy
  - buildDockerImageArticleService
  - buildDockerImageTopicService
  - buildDockerImageUserService
  - testArticleService
  - testTopicService
  - testUserService
  - deploy 

build:
  stage: dockerComposeLocalDeploy
  tags: 
    - CI/CD
  script:
    - echo "Docker compose deployment"
    - cd Backend
    - cp $ENV_FILE_DOCKER_COMPOSE .env
    - docker compose up 
  when: manual


buildDockerImageArticleService:
  stage: buildDockerImageArticleService
  tags: 
    - CI/CD
  before_script:
    - echo "Running before script"
    - docker login -u $docker_username -p $docker_access_token
  script:
    - echo creating/updating docker image for article_service and uploading to DockerHub 
    - cd Backend/article_service
    - docker build . -t lyutenitsa5/article_service:latest
    - docker push lyutenitsa5/article_service:latest
  only:
    changes:
      - Backend/article_service/**/*


buildDockerImageTopicService:
  stage: buildDockerImageTopicService
  tags: 
    - CI/CD
  before_script:
    - echo "Running before script"
    - docker login -u $docker_username -p $docker_access_token
  script:
    - echo creating/updating docker image for topic_service and uploading to DockerHub
    - cd Backend/topic_service
    - docker build . -t lyutenitsa5/topic_service:latest
    - docker push lyutenitsa5/topic_service:latest
  only:
    changes:
      - Backend/topic_service/**/*


buildDockerImageUserService:
  stage: buildDockerImageUserService
  tags: 
    - CI/CD
  before_script:
    - echo "Running before script"
    - docker login -u $docker_username -p $docker_access_token
  script:
    - echo creating/updating docker image for user_service and uploading to DockerHub
    - cd Backend/user_service
    - docker build . -t lyutenitsa5/user_service:latest
    - docker push lyutenitsa5/user_service:latest
  only:
    changes:
      - Backend/user_service/**/*


testArticleService: 
  image: python:3.9-slim-buster
  stage: testArticleService
  tags: 
    - docker_runner
  script:
    - echo "This is test pipepline for article_service"
    - cd Backend/article_service
    - echo $ENV_FILE_ARTICLE_SERVICE
    - cp $ENV_FILE_ARTICLE_SERVICE .env_local
    - pip install -r requirements.txt
    - pytest
  only:
    changes:
      - Backend/article_service/**/*


testTopicService:
  image: python:3.9-slim-buster
  stage: testTopicService
  tags: 
    - docker_runner
  script:
    - echo "This is test pipepline for topic_service"
    - cd Backend/topic_service
    - cp $ENV_FILE_TOPIC_SERVICE .env_local
    - pip install -r requirements.txt
    - pytest
  only:
    changes:
      - Backend/topic_service/**/*


testUserService:
  image: python:3.9-slim-buster
  stage: testUserService 
  tags: 
    - docker_runner
  script:
    - echo "This is test pipepline for user_service"
    - cd Backend/user_service
    - cp $ENV_FILE_USER_SERVICE .env_local
    - pip install -r requirements.txt
    - pytest
  only:
    changes:
      - Backend/user_service/**/*


deploy:
  image: google/cloud-sdk
  stage: deploy
  tags: 
   - docker_runner
  script:
    - echo "testing deploy job"
    - cp $gcloud_key_file gcloud-key.json
    - gcloud auth activate-service-account --key-file=gcloud-key.json
    - gcloud config set project nl-mama-project
    - gcloud config set container/cluster private-cluster-0
    - gcloud config set compute/zone europe-west1-d

    - gcloud container clusters get-credentials private-cluster-0 --zone europe-west1-d --project nl-mama-project
    # - sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" deployment.yaml
    - kubectl apply -f gcloud-deployment.yaml





  
