apiVersion: apps/v1
kind: Deployment
metadata:
  name: article_service
  labels:
    app: nl-mama_article_service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nl-mama_article_service
  template:
    metadata:
      labels:
        app: nl-mama_article_service
    spec:
      containers:
        - name: python-article-service
          image: lyutenitsa5/article_service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: nl-mama-service_article_service
  labels:
    app: nl-mama_article_service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: nl-mama_article_service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: topic_service
  labels:
    app: nl-mama_topic_service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nl-mama_topic_service
  template:
    metadata:
      labels:
        app: nl-mama_topic_service
    spec:
      containers:
        - name: python-topic_service
          image: lyutenitsa5/topic_service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: nl-mama-service_topic_service
  labels:
    app: nl-mama_topic_service
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: nl-mama_topic_service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user_service
  labels:
    app: nl-mama_user_service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nl-mama_user_service
  template:
    metadata:
      labels:
        app: nl-mama_user_service
    spec:
      containers:
        - name: python-user_service
          image: lyutenitsa5/user_service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          readinessProbe:
            httpGet:
              path: /
              port: 8082
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: nl-mama-service_user_service
  labels:
    app: nl-mama_user_service
spec:
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: nl-mama_user_service
