apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-gke-cicd
  labels:
    app: nl-mama
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nl-mama
  template:
    metadata:
      labels:
        app: nl-mama
    spec:
      containers:
        - name: python-article-service
          image: lyutenitsa5/article_service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
        - name: python-topic-service
          image: lyutenitsa5/topic_service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /
              port: 8082
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
        - name: python-user-service
          image: lyutenitsa5/user_service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          readinessProbe:
            httpGet:
              path: /
              port: 8082
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: nl-mama-service
  labels:
    app: nl-mama
spec:
  ports:
    - port: 8080
      targetPort: 8080
    - port: 8081
      targetPort: 8081
    - port: 8082
      targetPort: 8082
  selector:
    app: nl-mama
