apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - name: python-article-service
          image: lyutenitsa5/article_service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
        - name: python-topic-service
          image: lyutenitsa5/topic_service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /
              port: 8082
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
        - name: python-user-service
          image: lyutenitsa5/user_service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          readinessProbe:
            httpGet:
              path: /
              port: 8082
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: python-service
  labels:
    app: python
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: python
