apiVersion: apps/v1
kind: Deployment
metadata:
  name: topic-service
  labels:
    app: nl-mama-topic-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nl-mama-topic-service
  template:
    metadata:
      labels:
        app: nl-mama-topic-service
    spec:
      containers:
        - name: python-article-service
          image: lyutenitsa5/topic_service:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "500Mi"

          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: nl-mama-service-topic-service
  labels:
    app: nl-mama-topic-service
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: nl-mama-topic-service