apiVersion: apps/v1
kind: Deployment
metadata:
  name: user_service
  labels:
    app: nl-mama_user_service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nl-mama_user_service
  template:
    metadata:
      labels:
        app: nl-mama_user_service
    spec:
      containers:
        - name: python-article-service
          image: lyutenitsa5/user_service:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "500Mi"
          ports:
            - containerPort: 8082
          readinessProbe:
            httpGet:
              path: /
              port: 8082
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: nl-mama-service_user_service
  labels:
    app: nl-mama_user_service
spec:
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: nl-mama_user_service