swagger: '2.0'
info:
  title: gateway-test
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /user:
    get:
      summary: Testing config
      operationId: test
      x-google-backend:
        address: http://34.142.121.21:8082
      responses:
        '200':
          description: A successful response