"""initial migration

Revision ID: 6a08191452f2
Revises: 
Create Date: 2022-11-10 01:33:07.541429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID
import uuid


# revision identifiers, used by Alembic.
revision = '6a08191452f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'articles',
        sa.Column(
            'id',
            UUID,
            default=uuid.uuid4,
            primary_key=True,
            unique=True,
            server_default=sa.text('gen_random_uuid()')
        ),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('content', sa.String(), nullable=False),
        
        sa.Column('author_user_id', UUID, unique=True, nullable=False),
        sa.Column('topic_id', UUID, unique=True, nullable=False),
        
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    # ### end Alembic commands ###
