"""initial migration

Revision ID: 37e3eb26a2b9
Revises: 
Create Date: 2022-11-09 23:14:50.452651

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID
import uuid


# revision identifiers, used by Alembic.
revision = '37e3eb26a2b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		'users',
		sa.Column(
			'id',
			UUID,
			default=uuid.uuid4,
			primary_key=True,
			unique=True,
			server_default=sa.text('gen_random_uuid()')
		),
		sa.Column('username', sa.String(), nullable=False),
		sa.Column('password', sa.String(), nullable=False),
		sa.Column('first_name', sa.String(), nullable=False),
		sa.Column('last_name', sa.String(), nullable=False),
		sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
		sa.PrimaryKeyConstraint('id')
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table('users')
	# ### end Alembic commands ###
